from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
from local_tools import calculator_tool, system_status_tool, list_project_files, read_project_file


@tool
def search_agent_tool(query: str, thread_id: str = "search_thread") -> str:
    """Utilizza l'agente di ricerca per cercare informazioni."""
    from search_agent.search_graph import create_search_graph

    search_app = create_search_graph()
    config = {"configurable": {"thread_id": thread_id}}
    state = {"messages": [HumanMessage(content=query)]}
    result = search_app.invoke(state, config=config)
    return result["messages"][-1].content


@tool
def calendar_agent_tool(query: str, thread_id: str = "calendar_thread") -> str:
    """Consulta e gestisce Google Calendar quando è configurato."""
    from calendar_agent.calendar_graph import graph as calendar_app

    config = {"configurable": {"thread_id": thread_id}}
    state = {"messages": [HumanMessage(content=query)]}
    result = calendar_app.invoke(state, config=config)
    return result["messages"][-1].content


@tool
def email_agent_tool(query: str, thread_id: str = "email_thread") -> str:
    """Consulta e prepara email quando Gmail è configurato."""
    from email_agent.email_connector import fetch_emails
    from email_agent.agent.email_graph import graph as email_app

    recent_emails = fetch_emails()
    config = {"configurable": {"thread_id": thread_id}}
    state = {
        "emails": recent_emails,
        "messages": [HumanMessage(content=query)],
        "revision_count": 0,
    }
    result = email_app.invoke(state, config=config)
    return result["messages"][-1].content


supervisor_tools = [
    calculator_tool,
    system_status_tool,
    list_project_files,
    read_project_file,
    search_agent_tool,
    calendar_agent_tool,
    email_agent_tool,
]
# Generated by Copilot
