import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React from 'react';
import {create,act} from 'react-test-renderer';
const require=createRequire(import.meta.url);
const external=n=>JSON.stringify(pathToFileURL(require.resolve(n)).href);
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const node=(id,kind='agent')=>({id,kind,name:id,description:'Description '+id,available:true,capabilities:[],model:kind==='agent'?'local-model':null});
const fixture={version:'v1',framework:'LangGraph',nodes:[node('react_ui','interface'),node('fastapi_backend','interface'),node('supervisor'),node('structure_agent'),node('local_research_agent'),node('audio_agent'),node('email_quotes_agent')],edges:[{source:'react_ui',target:'fastapi_backend',kind:'request',label:'Chat'},{source:'fastapi_backend',target:'supervisor',kind:'request',label:'/chat'},...['structure_agent','local_research_agent','audio_agent','email_quotes_agent'].map(target=>({source:'supervisor',target,kind:'delegation',label:'Delega'}))],components:[node('persistent_memory','core')],direct_paths:[{id:'calendar',name:'Calendario',trigger:'User',description:'Direct API',routes:[]}],automations:[{id:'persist',name:'Persistenza',trigger:'Chat',description:'Deterministico'}]};
let response=async()=>fixture;
globalThis.__overviewApi={architectureOverview:()=>response()};
const source=await readFile(new URL('../src/components/ArchitectureOverview.tsx',import.meta.url),'utf8');
const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/from "react\/jsx-runtime"/g,'from '+external('react/jsx-runtime')).replace(/from "react"/g,'from '+external('react')).replace('import { api } from "../services/api";','const api=globalThis.__overviewApi;').replace('import "./architecture-overview.css";','');
const Overview=(await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'))).default;
test('one system map, separate agents, real delegation edges and selection',async()=>{
 let r,selected;const props={health:null,selectedNode:'supervisor',onSelect:id=>{selected=id;}};
 await act(async()=>{r=create(React.createElement(Overview,props));});
 assert.equal(r.root.findAllByType('svg').length,1);
 const buttons=r.root.findAllByType('button').filter(b=>b.props.className?.startsWith('overview-node '));
 assert.equal(buttons.length,7);
 assert.equal(r.root.findAllByType('path').filter(p=>p.props.className==='delegation').length,4);
 await act(async()=>buttons.find(b=>b.findAllByType('strong')[0].children.includes('Documenti')).props.onClick());
 assert.equal(selected,'local_research_agent');
 await act(async()=>r.update(React.createElement(Overview,{...props,selectedNode:selected})));
 assert.ok(JSON.stringify(r.toJSON()).includes('Description local_research_agent'));
 assert.ok(JSON.stringify(r.toJSON()).includes('local-model'));
 assert.equal(r.root.findAllByProps({className:'overview-path'}).length,1);
 assert.ok(!JSON.stringify(r.toJSON()).includes('call_llm'));
 await act(async()=>r.unmount());
});
test('offline refresh removes old topology and retry restores it',async()=>{
 let r;await act(async()=>{r=create(React.createElement(Overview,{health:null,selectedNode:'supervisor',onSelect:()=>{}}));});
 response=async()=>{throw Error('Offline');};
 await act(async()=>r.root.findAllByType('button').find(b=>b.children.includes('Aggiorna')).props.onClick());
 assert.equal(r.root.findAllByProps({role:'alert'}).length,1);
 assert.equal(r.root.findAllByType('svg').length,0);
 response=async()=>fixture;
 await act(async()=>r.root.findByType('button').props.onClick());
 assert.equal(r.root.findAllByType('svg').length,1);
 await act(async()=>r.unmount());
});
