import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React from 'react';
import {act,create} from 'react-test-renderer';
const require=createRequire(import.meta.url);
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const fixture=[{name:'calculator_tool',group:'Sistema',description:'Calcolo',permissions:[{action:'calculate',policy:'auto'}]},{name:'calendar_create_event',group:'Calendario',description:'Proposta',permissions:[{action:'create',policy:'confirm'}]}];
let load=async()=>fixture;
globalThis.__chatTools=()=>load();
const src=await readFile(new URL('../src/components/ChatToolPicker.tsx',import.meta.url),'utf8');
const code=ts.transpileModule(src,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from "react\/jsx-runtime"/g,'from '+JSON.stringify(pathToFileURL(require.resolve('react/jsx-runtime')).href)).replace(/from "react"/g,'from '+JSON.stringify(pathToFileURL(require.resolve('react')).href)).replace('import { chatTools } from "../services/chatToolsApi";','const chatTools=globalThis.__chatTools;');
const Picker=(await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'))).default;
const button=(r,label)=>r.root.findAllByType('button').find(b=>b.children.includes(label));
test('manual choice distinguishes empty from automatic and exposes current permission policies',async()=>{
 let r,selection=null;const props=()=>({selection,onChange:n=>{selection=n;r.update(React.createElement(Picker,props()));},disabled:false,available:true});
 await act(async()=>{r=create(React.createElement(Picker,props()));});
 await act(async()=>r.root.findByType('button').props.onClick());
 await act(async()=>button(r,'Scelta manuale').props.onClick());
 assert.deepEqual(selection,[]);
 assert.ok(JSON.stringify(r.toJSON()).includes('Nessun tool abilitato'));
 await act(async()=>r.root.findAllByType('input')[0].props.onChange({target:{checked:true}}));
 assert.deepEqual(selection,['calculator_tool']);
 assert.ok(JSON.stringify(r.toJSON()).includes('Automatico · nessuna conferma'));
 assert.ok(JSON.stringify(r.toJSON()).includes('Conferma prevista'));
 await act(async()=>button(r,'Automatici').props.onClick());
 assert.equal(selection,null);
 await act(async()=>r.unmount());
});
test('catalog failure stays visible and retry recovers without changing manual selection',async()=>{
 load=async()=>{throw Error('offline');};let r;const changes=[];
 await act(async()=>{r=create(React.createElement(Picker,{selection:['calculator_tool'],onChange:n=>changes.push(n),disabled:false,available:true}));});
 await act(async()=>r.root.findByType('button').props.onClick());
 assert.equal(r.root.findAllByProps({role:'alert'}).length,1);
 load=async()=>fixture;await act(async()=>button(r,'Riprova').props.onClick());
 assert.equal(r.root.findAllByProps({role:'alert'}).length,0);assert.deepEqual(changes,[]);
 await act(async()=>r.unmount());
});
